# .sops.yaml
keys:
  # Generated public age key
  - &zachary age1fn9ed07qzpk3cc75c87qydmvf2lytrn5dvlcytu6cv3namec5gqsevxnpr
  # - &sarah GPG_KEY # Replace with queen's public SSH key

# Default creation rule: Encrypt new files using the master key AND
# the host keys for ALL hosts defined above. This allows editing with the
# master key, and decryption by any specified host.
creation_rules:
  - path_regex: secrets.yaml$ # Or adjust path/name as needed
    # You can also use '.*' to match any file sops manages
    key_groups:
      - age:
          - *zachary

  # Example for host-specific secrets (optional)
  # - path_regex: secrets/king-secrets.yaml$
  #   key_groups:
  #     - age:
  #         - *master_key # Still allow editing with master key
  #       ssh:
  #         - *king_host # Only king can decrypt this one

  # - path_regex: secrets/queen-secrets.yaml$
  #   key_groups:
  #     - age:
  #         - *master_key
  #       ssh:
  #         - *queen_host
